name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean Install Dependencies
      run: npm ci

    - name: Install S3 Upload Packages
      run: npm install multer multer-s3 @aws-sdk/client-s3

    - name: Restart with PM2
      run: pm2 restart Backend
